import { StyleSheet } from 'react-native';
import { theme } from '../../styles/theme';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingBottom: 0,
    backgroundColor: theme.colors.overlay
  },
  outsidePressable: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0 },
  modal: {
    width: '100%',
    maxWidth: 560,
    maxHeight: '92%',
    overflow: 'hidden',
    zIndex: 1,
    elevation: 1,
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: theme.radius.lg,
    borderTopRightRadius: theme.radius.lg,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    borderBottomWidth: 0
  },
  sheetHandleArea: { height: 20, alignItems: 'center', justifyContent: 'center' },
  sheetHandle: { width: 38, height: 4, borderRadius: theme.radius.pill, backgroundColor: theme.colors.outline },
  header: {
    minHeight: 62,
    paddingHorizontal: theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  brandIcon: {
    width: 42,
    height: 42,
    borderRadius: theme.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.secondary
  },
  closeButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface
  },
  content: { paddingHorizontal: theme.spacing.lg, paddingBottom: theme.spacing.md, gap: theme.spacing.sm },
  title: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 22, lineHeight: 30 },
  subtitle: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 15, lineHeight: 23 },
  promise: { padding: theme.spacing.md, borderRadius: theme.radius.md, backgroundColor: theme.colors.successSoft },
  promiseText: { color: theme.colors.success, fontFamily: theme.typography.semibold, fontSize: 13, lineHeight: 20 },
  benefit: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, paddingVertical: theme.spacing.xxs },
  benefitText: { flex: 1, color: theme.colors.foreground, fontFamily: theme.typography.medium, fontSize: 14, lineHeight: 21 },
  statusNotice: { gap: theme.spacing.sm, padding: theme.spacing.md, borderRadius: theme.radius.md, backgroundColor: theme.colors.surface },
  statusText: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 13, lineHeight: 20 },
  activeNotice: { gap: theme.spacing.xxs, padding: theme.spacing.md, borderRadius: theme.radius.md, backgroundColor: theme.colors.successSoft },
  activeTitle: { color: theme.colors.success, fontFamily: theme.typography.bold, fontSize: 15 },
  errorText: { color: theme.colors.danger, fontFamily: theme.typography.medium, fontSize: 13, lineHeight: 19 },
  plansHeading: { marginTop: theme.spacing.xs, color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 15 },
  plans: { flexDirection: 'row', gap: theme.spacing.xs },
  planCard: { flex: 1, minWidth: 0, alignItems: 'center', gap: theme.spacing.xs, paddingVertical: theme.spacing.sm, paddingHorizontal: theme.spacing.xxs, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.outline, backgroundColor: theme.colors.surface },
  planTitle: { color: theme.colors.foreground, fontFamily: theme.typography.semibold, fontSize: 12, textAlign: 'center' },
  comingSoon: { paddingVertical: 4, paddingHorizontal: theme.spacing.xs, borderRadius: theme.radius.pill, backgroundColor: theme.colors.surfaceMuted },
  comingSoonText: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 10 },
  futureNote: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 11, lineHeight: 16 },
  likesGate: { flex: 1, justifyContent: 'center', gap: theme.spacing.md, paddingHorizontal: theme.spacing.md, paddingBottom: theme.spacing.xl },
  likesGateIcon: { width: 56, height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: theme.radius.pill, backgroundColor: theme.colors.primarySoft },
  likesGateTitle: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 21, lineHeight: 29 },
  likesGateDescription: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 14, lineHeight: 22 },
  profileCard: { gap: theme.spacing.sm, backgroundColor: theme.colors.surfaceMuted, borderColor: theme.colors.outline },
  profileCardHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.sm },
  profileIcon: { width: 38, height: 38, borderRadius: theme.radius.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.surface },
  profileCardCopy: { flex: 1, gap: theme.spacing.xxs },
  profileCardTitle: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 15, lineHeight: 21 },
  profileCardDescription: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 12, lineHeight: 19 },
});
