import { StyleSheet } from 'react-native';
import { theme } from '../../styles/theme';

export const styles = StyleSheet.create({
  screen: { width: '100%', maxWidth: 672, alignSelf: 'center' },
  scroll: { paddingBottom: theme.spacing.xl, gap: theme.spacing.lg },
  bookList: { paddingBottom: theme.spacing.xl, gap: theme.spacing.md },
  listHeader: { gap: theme.spacing.lg },
  introStack: { gap: theme.spacing.md },
  editButton: { minHeight: 48, paddingHorizontal: theme.spacing.sm, borderRadius: theme.radius.pill },
  identity: { gap: theme.spacing.md, paddingVertical: theme.spacing.xs },
  identityRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.md },
  identityStacked: { flexDirection: 'column', alignItems: 'flex-start' },
  identityCopy: { flex: 1, minWidth: 0, gap: theme.spacing.xs },
  identityCopyStacked: { flexGrow: 0, flexShrink: 0, flexBasis: 'auto', width: '100%' },
  name: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 22, lineHeight: 29, flexShrink: 1 },
  location: { flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.xxs },
  locationText: { flex: 1, color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 13, lineHeight: 19 },
  bio: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 14, lineHeight: 22 },
  metrics: { paddingVertical: theme.spacing.sm, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.outline },
  collectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm },
  collectionStacked: { flexDirection: 'column', alignItems: 'stretch' },
  collectionCopy: { flexShrink: 1 },
  sectionTitle: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 18, lineHeight: 25 },
  addBook: { minHeight: 48, paddingHorizontal: theme.spacing.sm },
  bookRow: { gap: theme.spacing.md },
  footer: { alignItems: 'center', paddingTop: theme.spacing.xs },
  footerText: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 12 },
  aboutSection: { gap: theme.spacing.xs },
  aboutRow: { flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.sm, paddingVertical: theme.spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.outline },
  aboutCopy: { flex: 1, minWidth: 0, gap: theme.spacing.xxs },
  aboutLabel: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 12, lineHeight: 18 },
  aboutValue: { color: theme.colors.foreground, fontFamily: theme.typography.regular, fontSize: 14, lineHeight: 22 },
  accountSection: { gap: theme.spacing.md },
  signOut: { alignSelf: 'flex-start', paddingHorizontal: 0 },
  modalSafe: { flex: 1, backgroundColor: theme.colors.background },
  modalKeyboard: { flex: 1 },
  modalHeader: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: theme.spacing.md, borderBottomWidth: 1, borderBottomColor: theme.colors.outline, backgroundColor: theme.colors.surface },
  modalClose: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: theme.radius.md },
  modalPressed: { backgroundColor: theme.colors.surfaceMuted },
  modalTitle: { flexShrink: 1, color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 19 },
  modalHeaderSpacer: { width: 48, height: 48 },
  modalScroll: { padding: theme.spacing.md, paddingBottom: theme.spacing.xxl, gap: theme.spacing.md },
  editorIdentity: { alignItems: 'center', gap: theme.spacing.sm, paddingVertical: theme.spacing.sm },
  editorHint: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 12, lineHeight: 18, textAlign: 'center' }
});
