import { StyleSheet } from 'react-native';
import { theme } from '../../styles/theme';

export const styles = StyleSheet.create({
  scroll: { paddingBottom: theme.spacing.xxl, gap: theme.spacing.md },
  listHeader: { gap: theme.spacing.md, paddingBottom: theme.spacing.xs },
  introStack: { gap: theme.spacing.md },
  heroWrap: { gap: 0 },
  identityCard: { alignItems: 'center', marginHorizontal: theme.spacing.sm, marginTop: -30, paddingHorizontal: theme.spacing.md, paddingTop: 44, paddingBottom: theme.spacing.lg, borderRadius: theme.radius.lg, borderWidth: 1, borderColor: theme.colors.outline, backgroundColor: theme.colors.surface, shadowColor: theme.shadow.color, shadowOpacity: theme.shadow.opacity, shadowRadius: theme.shadow.radius, shadowOffset: theme.shadow.offset, elevation: theme.shadow.elevation },
  avatarFrame: { marginTop: -62, padding: 4, borderRadius: theme.radius.pill, backgroundColor: theme.colors.surface, shadowColor: theme.shadow.color, shadowOpacity: theme.shadow.opacity, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  name: { color: theme.colors.foreground, fontFamily: theme.typography.extraBold, fontSize: 24, lineHeight: 30, textAlign: 'center' },
  location: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xxs, marginTop: theme.spacing.xxs },
  locationText: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 13 },
  bio: { maxWidth: 310, color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: theme.spacing.xs },
  metricCard: { paddingVertical: theme.spacing.sm, paddingHorizontal: theme.spacing.xs },
  collectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm, paddingTop: theme.spacing.xs },
  collectionCopy: { flex: 1, gap: theme.spacing.xxs },
  eyebrow: { color: theme.colors.primary, fontFamily: theme.typography.bold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.1 },
  sectionTitle: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 19, lineHeight: 24 },
  addBook: { minHeight: 46, paddingHorizontal: theme.spacing.sm },
  bookList: { paddingBottom: 112, gap: theme.spacing.md },
  bookRow: { gap: theme.spacing.md },
  bookItem: { width: '47.7%' },
  footer: { alignItems: 'center', paddingVertical: theme.spacing.lg, gap: theme.spacing.xs },
  footerText: { color: theme.colors.mutedForeground, fontFamily: theme.typography.medium, fontSize: 12 },
  aboutCard: { gap: theme.spacing.md },
  aboutIntro: { gap: theme.spacing.xs, paddingBottom: theme.spacing.xs },
  aboutTitle: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 18, lineHeight: 24 },
  aboutRow: { flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.sm, paddingVertical: theme.spacing.xs, borderTopWidth: 1, borderTopColor: theme.colors.surfaceMuted },
  aboutCopy: { flex: 1, gap: 2 },
  aboutLabel: { color: theme.colors.mutedForeground, fontFamily: theme.typography.semibold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.7 },
  aboutValue: { color: theme.colors.foreground, fontFamily: theme.typography.regular, fontSize: 14, lineHeight: 21 },
  modalSafe: { flex: 1, backgroundColor: theme.colors.background },
  modalKeyboard: { flex: 1 },
  modalHeader: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: theme.spacing.md, borderBottomWidth: 1, borderBottomColor: theme.colors.outline, backgroundColor: theme.colors.surface },
  modalClose: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: theme.radius.md },
  modalPressed: { backgroundColor: theme.colors.surfaceMuted },
  modalTitle: { color: theme.colors.foreground, fontFamily: theme.typography.extraBold, fontSize: 19 },
  modalHeaderSpacer: { width: 48, height: 48 },
  modalScroll: { padding: theme.spacing.md, paddingBottom: theme.spacing.xxl, gap: theme.spacing.md },
  editorIdentity: { alignItems: 'center', gap: theme.spacing.sm, paddingVertical: theme.spacing.sm },
  editorAvatar: { padding: 4, borderRadius: theme.radius.pill, backgroundColor: theme.colors.surface, shadowColor: theme.shadow.color, shadowOpacity: theme.shadow.opacity, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  editorHint: { maxWidth: 320, color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 12, lineHeight: 18, textAlign: 'center' }
});
