import { StyleSheet } from 'react-native';
import { theme } from '../../styles/theme';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.background },
  body: { flexGrow: 1, padding: theme.spacing.lg, justifyContent: 'space-between' },
  brand: { color: theme.colors.primary, fontFamily: theme.typography.extraBold, fontSize: 18, letterSpacing: -0.5 },
  hero: { gap: theme.spacing.lg },
  mark: { width: 84, height: 84, borderRadius: 26, backgroundColor: theme.colors.primary, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-4deg' }] },
  title: { color: theme.colors.foreground, fontFamily: theme.typography.extraBold, fontSize: 40, lineHeight: 46, letterSpacing: -1.8 },
  accent: { color: theme.colors.primary },
  description: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 16, lineHeight: 25, maxWidth: 360 },
  actions: { gap: theme.spacing.sm },
  finePrint: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: theme.spacing.xs },
  keyboard: { flex: 1 },
  formScroll: { flexGrow: 1, padding: theme.spacing.lg, paddingBottom: theme.spacing.xxl, gap: theme.spacing.lg },
  authTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  authBrand: { color: theme.colors.primary, fontFamily: theme.typography.extraBold, fontSize: 18, letterSpacing: -0.5 },
  backButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xs, paddingRight: theme.spacing.sm },
  backLabel: { color: theme.colors.foreground, fontFamily: theme.typography.semibold, fontSize: 13 },
  formIntro: { gap: theme.spacing.xs },
  formMark: { width: 42, height: 42, borderRadius: 14, backgroundColor: theme.colors.secondary, alignItems: 'center', justifyContent: 'center', marginBottom: theme.spacing.xs },
  formEyebrow: { color: theme.colors.primary, fontFamily: theme.typography.bold, fontSize: 12, letterSpacing: 1, textTransform: 'uppercase' },
  formTitle: { color: theme.colors.foreground, fontFamily: theme.typography.extraBold, fontSize: 30, lineHeight: 36, letterSpacing: -1 },
  formDescription: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 15, lineHeight: 23, maxWidth: 390, marginTop: theme.spacing.xs },
  formCard: { width: '100%', maxWidth: 480, alignSelf: 'center', gap: theme.spacing.md },
  passwordField: { position: 'relative' },
  passwordInput: { paddingRight: 52 },
  passwordToggle: { position: 'absolute', right: theme.spacing.sm, top: 30, width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  inlineLink: { alignSelf: 'flex-start', minHeight: 28, justifyContent: 'center' },
  inlineLinkText: { color: theme.colors.primary, fontFamily: theme.typography.bold, fontSize: 13 },
  errorBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.xs, backgroundColor: theme.colors.dangerSoft, borderRadius: theme.radius.sm, padding: theme.spacing.sm },
  errorBannerText: { flex: 1, color: theme.colors.danger, fontFamily: theme.typography.semibold, fontSize: 13, lineHeight: 19 },
  stepTitle: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 18, lineHeight: 24 },
  stepDescription: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 14, lineHeight: 21 },
  emphasis: { color: theme.colors.foreground, fontFamily: theme.typography.semibold },
  stepActions: { alignItems: 'center', gap: theme.spacing.xs },
  captchaMount: { minHeight: 1 },
  socialAuth: { gap: theme.spacing.sm },
  socialDivider: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm },
  socialDividerLine: { flex: 1, height: 1, backgroundColor: theme.colors.outline },
  socialDividerText: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 11 },
  googleButton: { minHeight: 50, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.outline, backgroundColor: theme.colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: theme.spacing.sm, paddingHorizontal: theme.spacing.md },
  googleButtonDisabled: { opacity: 0.48 },
  googleLogo: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.white },
  googleLogoText: { color: '#4285F4', fontFamily: theme.typography.extraBold, fontSize: 18 },
  googleLabel: { color: theme.colors.foreground, fontFamily: theme.typography.semibold, fontSize: 14 },
  socialHint: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 11, lineHeight: 16, textAlign: 'center' },
  modeSwitch: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', gap: theme.spacing.xs },
  modeSwitchLabel: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 13 },
  legal: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 11, lineHeight: 16, textAlign: 'center' }
});
