import { StyleSheet } from 'react-native';
import { theme } from '../../styles/theme';
export const styles = StyleSheet.create({
  body: { flex: 1 },
  bodyContent: { flexGrow: 1, paddingTop: theme.spacing.xxs, paddingBottom: theme.spacing.sm },
  deck: { flex: 1, alignItems: 'center', overflow: 'hidden' },
  feedback: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' },
  feedbackIcon: { textShadowColor: theme.colors.black, textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 12 },
  saving: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, alignItems: 'center', justifyContent: 'center', gap: theme.spacing.sm, pointerEvents: 'none' },
  savingText: { fontFamily: theme.typography.regular, color: theme.colors.mutedForeground, fontSize: 14 },
  gesture: { width: '100%', maxWidth: 560, flex: 1, minHeight: 440 },
  gestureLandscape: { maxWidth: 860, minHeight: 280 },
  cardPressable: { flex: 1 },
  cardPressed: { opacity: 0.88 },
  card: { flex: 1, padding: 0, overflow: 'hidden', borderRadius: theme.radius.lg },
  ownerRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, padding: theme.spacing.sm, borderBottomWidth: 1, borderBottomColor: theme.colors.outline },
  ownerInfo: { flex: 1, gap: theme.spacing.xxs },
  ownerName: { color: theme.colors.foreground, fontFamily: theme.typography.bold, fontSize: 14 },
  ownerCity: { color: theme.colors.mutedForeground, fontFamily: theme.typography.regular, fontSize: 12 },
  cardContent: { flex: 1 },
  cardLandscape: { flexDirection: 'row' },
  cover: { flex: 1, minHeight: 220, width: '100%', backgroundColor: theme.colors.surfaceMuted },
  coverLandscape: { flex: 0, width: '44%', minHeight: 200 },
  badge: { position: 'absolute', top: theme.spacing.sm, left: theme.spacing.sm },
  photoCount: { position: 'absolute', bottom: theme.spacing.sm, right: theme.spacing.sm, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xxs, backgroundColor: theme.colors.surface, borderRadius: theme.radius.pill, paddingHorizontal: theme.spacing.sm, paddingVertical: theme.spacing.xs },
  photoCountText: { fontSize: 12, fontFamily: theme.typography.semibold, color: theme.colors.foreground },
  details: { padding: theme.spacing.md, gap: theme.spacing.xs },
  detailsLandscape: { flex: 1, justifyContent: 'center' },
  title: { color: theme.colors.foreground, fontFamily: theme.typography.extraBold, fontSize: 24, letterSpacing: -0.6 },
  author: { color: theme.colors.primary, fontFamily: theme.typography.semibold, fontSize: 14 },
  viewHint: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.xs, paddingTop: theme.spacing.xxs },
  viewHintText: { color: theme.colors.primary, fontFamily: theme.typography.semibold, fontSize: 13 },
  actions: { flexDirection: 'row', justifyContent: 'center', gap: theme.spacing.lg, paddingTop: theme.spacing.sm },
  action: { width: 62, height: 62, borderRadius: 31, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.outline },
  like: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  disabled: { opacity: 0.48 },
  pressed: { backgroundColor: theme.colors.surfaceMuted },
  likePressed: { backgroundColor: theme.colors.primaryPressed }
});
